using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.Build.Evaluation;
using Microsoft.Build.Construction;
using System.Text.RegularExpressions;

namespace SourceCombiner
{
    public sealed class SourceCombiner
    {
        private static readonly List<string> SourceFilesToIgnore = new List<string>
        {
            "AssemblyInfo.cs"
        };

        static void Main(string[] args)
        {
            if (args == null || args.Length < 2)
            {
                //TODO Make a real cmd line parse tool with help args etc...
                Console.WriteLine("You must provide at least 2 arguments. " +
                                  "The first is the solution file path and the second is the output file path. " +
                                  "There is an optional third and fourth parameter. " +
                                  "The third indicates if the output file should be opened upon completion. " +
                                  "The fourth parameter indicates whether minification should be applied.");
                return;
            }

            string projectFilePath = args[0];
            string outputFilePath = args[1];

            bool openFile = false;
            if (args.Length > 2)
            {
                Boolean.TryParse(args[2],out openFile);
            }

            bool minify = false;
            if (args.Length > 3)
            {
                Boolean.TryParse(args[3], out minify);
            }

            var filesToParse = GetSourceFileNames(projectFilePath);
            var namespaces = GetUniqueNamespaces(filesToParse);

            string outputSource = GenerateCombinedSource(namespaces,filesToParse);

            if (minify)
            {
                outputSource = StripComments(outputSource);
                outputSource = StripWhitespace(outputSource);
            }

            File.WriteAllText(outputFilePath,outputSource);

            if (openFile)
            {
                Process.Start(outputFilePath);
            }
        }

        private static string GenerateCombinedSource(List<string> namespaces,List<string> files)
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine(@"/*");
            sb.AppendLine($" * File generated by SourceCombiner.exe using {files.Count} source files.");
            sb.AppendLine($" * Created On: {DateTime.Now}");
            sb.AppendLine(@"*/");

            foreach (var ns in namespaces.OrderBy(s => s))
            {
                sb.AppendLine("using " + ns + ";");
            }

            foreach (var file in files)
            {
                IEnumerable<string> sourceLines = File.ReadAllLines(file);
                sb.AppendLine(@"//*** SourceCombiner -> original file " + Path.GetFileName(file) + " ***");
                var usingDirectiveStartsWith = "using ";
                foreach (var sourceLine in sourceLines)
                {
                    var trimmedLine = sourceLine.Trim().Replace("  ", " ");
                    var isUsingDirective = trimmedLine.StartsWith(usingDirectiveStartsWith) && trimmedLine.EndsWith(";");
                    if (!string.IsNullOrWhiteSpace(sourceLine) && !isUsingDirective)
                    {
                        sb.AppendLine(sourceLine);
                    }
                }
            }
    
            return sb.ToString();
        }

        private static List<string> GetSourceFileNames(string solutionFilePath)
        {
            List<string> files = new List<string>();
            SolutionFile solutionFile = SolutionFile.Parse(solutionFilePath);
            foreach (Project project in solutionFile.ProjectsInOrder.Select(p => new Project(p.AbsolutePath)))
            {
                foreach (ProjectItem item in project.AllEvaluatedItems.Where(item => item.ItemType == "Compile"))
                {
                    if (!SourceFilesToIgnore.Contains(Path.GetFileName(item.EvaluatedInclude)))
                    {
                        string projectFolder = Path.GetDirectoryName(project.FullPath);
                        string fullpath = Path.Combine(projectFolder, item.EvaluatedInclude);
                        files.Add(fullpath);
                    }
                }
            }

            return files;
        }


        private static List<string> GetUniqueNamespaces(List<string> files)
        {
            var names = new List<string>();
            const string openingTag = "using ";
            const int namespaceStartIndex = 6;

            foreach (var file in files)
            {
                IEnumerable<string> sourceLines = File.ReadAllLines(file);

                foreach (var sourceLine in sourceLines)
                {
                    var trimmedLine = sourceLine.Trim().Replace("  ", " ");
                    if (trimmedLine.StartsWith(openingTag) && trimmedLine.EndsWith(";"))
                    {
                        var name = trimmedLine.Substring(namespaceStartIndex, trimmedLine.Length - namespaceStartIndex - 1);

                        if (!names.Contains(name))
                        {
                            names.Add(name);
                        }
                    }
                }
            }

            return names;
        }

        /// <summary>Removes all comments from the source text</summary>
        /// <param name="source">The source file loaded into a string</param>
        /// <returns>A new string where all comments have been removed</returns>
        /// <remarks>https://stackoverflow.com/a/3524689/1363780</remarks>
        private static string StripComments(string source)
        {
            var cleanedSource = string.Empty;

            var blockComments = @"/\*(.*?)\*/";
            var lineComments = @"//(.*?)\r?\n";
            var strings = @"""((\\[^\n]|[^""\n])*)""";
            var verbatimStrings = @"@(""[^""]*"")+";

            var pattern = blockComments + "|" + lineComments + "|" + strings + "|" + verbatimStrings;
            var matchEvaluator = new MatchEvaluator(CommentEvaluator);

            cleanedSource = Regex.Replace(source, pattern ,matchEvaluator,RegexOptions.Singleline);

            return cleanedSource;
        }

        //MatchEvaluator Delegate: https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.matchevaluator?view=netframework-4.7.2
        private static string CommentEvaluator(Match match)
        {
            if (match.Value.StartsWith("/*") || match.Value.StartsWith("//"))
            {
                return string.Empty;// m.Value.StartsWith("//") ? Environment.NewLine : "";
            }
            return match.Value; // Keep the literal strings
        }


        private static string StripWhitespace(string source)
        {
            //Replace all the newlines
            var cleaned = source.Replace(Environment.NewLine, string.Empty);

            //It would be nice to also strip extra spaces and tabs

            return cleaned;
        }
    }
}
